name: antlr
channels:
  - conda-forge
dependencies:
  - PyYAML=5.1.2                # yaml plparse
  - jsonpickle=1.2         # serialization of JSON to file
  - pip
  - pip:
      - antlr4-python3-runtime  # antlr plparse runtime
      - fastapi==0.55.1         # OpenAuth 3.x and Swagger API lib
      - pandas                  # dataframe processing and generation
      - tabulate==0.8.7         # pretty printer for pandas dataframe
      - graphviz==0.14          # create visual graphs in Jupyter. Available in other versions in conda as python-plgraph
      - plac==1.2.0             # simple command line arguments
