### ******************************************************************************************
###                                        WARNING
###                             all style values must be strings
###
### References:
###   1. Graphviz Colors
###      https://www.graphviz.org/doc/info/colors.html
### ******************************************************************************************

graph:
  split_text: True

nodes: # node style
  - node:
      conditions:
        type: misc
      style:
        shape: 'rectangle'
        width: '1.5'
        fixedsize: 'true'
        fontcolor: 'black'
        fontsize: '10'
        colorscheme: 'blues9'
        color: '2'
        style: 'filled'
  - node:
      conditions:
        type: context
      style:
        shape: 'rectangle'
        width: '1.5'
        fixedsize: 'true'
        fontcolor: 'black'
        colorscheme: 'blues9'
        color: '3'
        style: 'filled'
  - node:
      conditions:
        type: date
      style:
        shape: 'rectangle'
        width: '1.5'
        fixedsize: 'true'
        fontcolor: 'black'
        fontsize: '10'
        colorscheme: 'blues9'
        color: '4'
        style: 'filled'
  - node:
      conditions:
        type: nlp
      style:
        shape: 'rectangle'
        width: '1.5'
        fixedsize: 'true'
        fontcolor: 'black'
        fontsize: '10'
        colorscheme: 'blues9'
        color: '5'
        style: 'filled'
  - node:
      conditions:
        type: patterns
      style:
        shape: 'rectangle'
        width: '1.5'
        fixedsize: 'true'
        fontcolor: 'black'
        fontsize: '10'
        colorscheme: 'blues9'
        color: '6'
        style: 'filled'
  - node:
      conditions:
        type: synonym
      style:
        shape: 'rectangle'
        width: '1.5'
        fixedsize: 'true'
        fontcolor: 'black'
        fontsize: '10'
        colorscheme: 'blues9'
        color: '7'
        style: 'filled'
  - node:
      conditions:
        type: util
      style:
        shape: 'rectangle'
        width: '1.5'
        fixedsize: 'true'
        fontcolor: 'black'
        fontsize: '10'
        colorscheme: 'blues9'
        color: '8'
        style: 'filled'
                    

  - node:
      conditions:
        type: clause
      style:
        shape: 'record'
        style: 'rounded'
        fontcolor: 'black'
        fontsize: '8'
        fillcolor: 'yellow'
        text: '{Clause|P0}'
  - node:
      conditions:
        type: conjunction
      style:
        shape: 'record'
        fixedsize: 'false'
        colorscheme: 'blues9'
        color: '6'
        text: 'AND|{P0}'
        width: '0.50'
        height: '0.50'
  - node:
      conditions:
        type: conditional
      style:
        shape: 'plaintext'
        text: 'IF'
  - node:
      conditions:
        type: compound
      style:
        shape: 'ellipse'
        colorscheme: 'blues9'
        color: '6'
        width: '0.25'
        height: '0.25'
        text: 'compound'
  - node:
      conditions:
        type: entity
      style:
        shape: 'atomic'
        colorscheme: 'blues9'
        color: '6'
        width: '0.10'
        height: '0.10'
        text: 'entity'
  - node:
      conditions:
        type: record
      style:
        shape: 'terminator'
        fixedsize: 'true'
        colorscheme: 'blues9'
        color: '4'
        fontcolor: 'black'
        fontsize: '10'
  - node:
      conditions:
        type: atomic
      style:
        shape: 'point'
        fixedsize: 'true'
        colorscheme: 'blues9'
        color: '4'
        fontcolor: 'black'
        fontsize: '6'
  - node:
      conditions:
        type: operator
      style:
        shape: 'diamond'
        fixedsize: 'true'
        colorscheme: 'blues9'
        color: '8'
        fontcolor: 'white'
        fontsize: '8'
  - node: # default style
      style:
#        size: '800,800'
#        shape: 'oval'
#        color: 'lightblue2'
#        style: 'filled'
        fontsize: '8'

edges: # edge style
  - edge:
      predicate: calls
      display_label: False
      style:
        colorscheme: 'bupu9'
        color: '3'
        arrowhead: 'vee'
        style: 'dotted'
        arrowsize: '0.5'
  - edge:
      display_label: True
      style:
        color: 'black' # edge stroke color
        fontcolor: 'white' # type face color
        fontsize: '1' # point size of label
        arrowhead: 'normal' # style of arrowhead at head end
        arrowsize: '1.0' # scaling factor for arrowheads
        style: 'filled' # bold, dotted filled

