### ******************************************************************************************
###                                        WARNING
###                             all style values must be strings
###
### References:
###   1. Graphviz Colors
###      https://www.graphviz.org/doc/info/colors.html
### ******************************************************************************************

graph:
  split_text: True
  compound: True

nodes: # node style
  - node:
      conditions:
        type: string
      style:
        shape: 'doublecircle'
        colorscheme: 'blues9'
        color: '9'
        fixedsize: 'true'
        fontcolor: 'gray'
        fontsize: '8'
  - node:
      conditions:
        type: string_cluster
      style:
        shape: 'doublecircle'
        colorscheme: 'blues9'
        color: '5'
        fixedsize: 'true'
        fontcolor: 'black'
        fontsize: '10'

  - node:
      conditions:
        type: entity
      style:
        shape: 'doublecircle'
        colorscheme: 'blues9'
        color: '8'
        fixedsize: 'true'
        fontcolor: 'gray'
        fontsize: '8'
  - node:
      conditions:
        type: entity_cluster
      style:
        shape: 'doublecircle'
        colorscheme: 'blues9'
        color: '4'
        fixedsize: 'true'
        fontcolor: 'black'
        fontsize: '10'

  - node:
      conditions:
        type: variable
      style:
        shape: 'doublecircle'
        colorscheme: 'blues9'
        color: '7'
        fixedsize: 'true'
        fontcolor: 'gray'
        fontsize: '8'
  - node:
      conditions:
        type: variable_cluster
      style:
        shape: 'doublecircle'
        colorscheme: 'blues9'
        color: '3'
        fixedsize: 'true'
        fontcolor: 'black'
        fontsize: '10'

  - node: # default style
      style:
#        size: '800,800'
#        shape: 'oval'
#        color: 'lightblue2'
#        style: 'filled'
        fontsize: '8'

edges: # edge style
  - edge:
      predicate: label
      display_label: True
      style:
        colorscheme: 'bupu9'
        color: '3'
        arrowhead: 'vee'
        arrowsize: '0.5'
        fontsize: '8'
  - edge:
      predicate: parent
      display_label: True
      style:
        colorscheme: 'bupu9'
        color: '4'
        arrowhead: 'vee'
        style: 'solid'
        arrowsize: '1.0'
        fontsize: '8'
  - edge:
      predicate: ancestor
      display_label: True
      style:
        colorscheme: 'bupu9'
        color: '5'
        arrowhead: normal
        fontsize: '8'
        weight: '1.5'
  - edge:
      predicate: equivalent
      display_label: False
      style:
        style: 'dotted'
        colorscheme: 'greys9'
        color: '2'
        arrowhead: none
        fontsize: '5'
        weight: '0.5'
  - edge:
      predicate: definition
      display_label: False
      style:
        style: 'dotted'
        colorscheme: 'greys9'
        color: '3'
        arrowhead: none
        fontsize: '5'
        weight: '0.5'
  - edge:
      display_label: True
      style:
        color: 'black' # edge stroke color
        fontcolor: 'white' # type face color
        fontsize: '1' # point size of label
        arrowhead: 'normal' # style of arrowhead at head end
        arrowsize: '1.0' # scaling factor for arrowheads
        style: 'filled' # bold, dotted filled

