### ******************************************************************************************
###                                        WARNING
###                             all style values must be strings
###
### References:
###   1. Graphviz Colors
###      https://www.graphviz.org/doc/info/colors.html
###   2. Node, Edge and Graph Attributes
###      https://graphviz.org/doc/info/attrs.html
### ******************************************************************************************

nodes: # node style
  - issue:
      shape: 'point'
      fontsize: '10'
      fontname: 'Helvetica'
      fixedsize: 'True'
      height: '0.01'
      width: '0.01'
      colorscheme: 'paired9'
      color: '1'
      label: ' '
  - person:
      shape: 'circle'
      fontsize: '10'
      fontname: 'Helvetica'
      fixedsize: 'True'
      height: '1.00'
      width: '1.00'
      colorscheme: 'paired9'
      color: '7'
      display_label: True
edges:
   - collaborates:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '6'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
   - assignedto:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '6'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
   - assigns:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '5'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
   - contributedto:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '4'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
   - mentions:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '3'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
   - openedBy:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '2'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
   - closedBy:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '1'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
