### ******************************************************************************************
###                                        WARNING
###                             all style values must be strings
###
### References:
###   1. Graphviz Colors
###      https://www.graphviz.org/doc/info/colors.html
###   2. Node, Edge and Graph Attributes
###      https://graphviz.org/doc/info/attrs.html
### ******************************************************************************************

graph:
  split_text: False

nodes: # node style
  - issue:
      shape: 'record'
      fontsize: '10'
      fontname: 'Helvetica'
      fixedsize: 'True'
      height: '1.00'
      width: '2.50'
      colorscheme: 'paired9'
      color: '1'
      display_label: True
  - pull_request:
      shape: 'box3d'
      fontsize: '10'
      fontname: 'Helvetica'
      fixedsize: 'True'
      height: '0.50'
      width: '4.00'
      colorscheme: 'paired9'
      color: '2'
      display_label: True
  - commit:
      shape: 'record'
      fontsize: '10'
      fontname: 'Helvetica'
      fixedsize: 'True'
      height: '1.50'
      width: '2.00'
      colorscheme: 'paired9'
      color: '3'
      display_label: True
  - file_commit:
      shape: 'point'
      fontsize: '10'
      fontname: 'Helvetica'
      fixedsize: 'True'
      height: '0.10'
      width: '0.10'
      colorscheme: 'paired9'
      color: '4'
      display_label: True
  - file_name:
      shape: 'note'
      fontsize: '10'
      fontname: 'Helvetica'
      fixedsize: 'True'
      height: '0.50'
      width: '1.25'
      colorscheme: 'paired9'
      color: '5'
      display_label: True
  - file_folder:
      shape: 'folder'
      fontsize: '10'
      fontname: 'Helvetica'
      fixedsize: 'True'
      height: '0.50'
      width: '0.50'
      colorscheme: 'paired9'
      color: '6'
      display_label: True
  - person:
      shape: 'circle'
      fontsize: '10'
      fontname: 'Helvetica'
      fixedsize: 'True'
      height: '1.00'
      width: '1.00'
      colorscheme: 'paired9'
      color: '7'
      display_label: True

edges:
  - imports:
      arrowhead: 'none'
      arrowsize: '1.0'
      penwidth: '1'
      color: '2'
      colorscheme: 'purples9'
      style: 'dashed'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - composes:
      arrowhead: 'none'
      arrowsize: '1.0'
      penwidth: '1'
      color: '3'
      colorscheme: 'purples9'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - contains:
      arrowhead: 'none'
      arrowsize: '0.25'
      penwidth: '0.5'
      color: '4'
      colorscheme: 'purples9'
      style: 'dashed'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - modifies:
      arrowhead: 'none'
      arrowsize: '1.0'
      penwidth: '1'
      color: '5'
      colorscheme: 'purples9'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - has:
      arrowhead: 'none'
      arrowsize: '1.0'
      penwidth: '1'
      color: '6'
      colorscheme: 'purples9'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - commits:
      arrowhead: 'none'
      arrowsize: '1.0'
      penwidth: '1'
      color: '7'
      colorscheme: 'purples9'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - references:
      arrowhead: 'none'
      arrowsize: '1.0'
      penwidth: '1'
      color: '9'
      colorscheme: 'purples9'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - partOf:
      arrowhead: 'none'
      arrowsize: '1.0'
      penwidth: '1'
      color: '9'
      colorscheme: 'purples9'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True

  # SOCIAL NODES
  - assignedto:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '6'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - assigns:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '5'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - contributedto:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '4'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - mentions:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '3'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - openedBy:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '2'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
  - closedBy:
      arrowhead: 'vee'
      arrowsize: '1.0'
      penwidth: '1'
      color: '1'
      colorscheme: 'ylgnbu6'
      style: 'solid'
      constraint: 'true'
      fontsize: '8'
      fontname: 'Helvetica'
      display_label: True
