input: 
    path: '/home/craig/git/prolognlp/'
    modules:
        - name: nlp
          path: cl/nlp/nlp.pro
        - name: misc
          path: cl/misc/misc.pro
        - name: context
          path: cl/context/context.pro
        - name: date
          path: cl/date/date.pro
        - name: patterns
          path: cl/patterns/patterns.pro
        - name: synonym
          path: cl/synonym/synonym.pro
        - name: util
          path: cl/util/util.pro
output:
    path: 'resources/output/prolog'
    modules:
        - name: misc
          path: misc/functions/03 tsv
        # - name: context
        #   path: context/functions/03 tsv
        # - name: date
        #   path: date/functions/03 tsv
        # - name: nlp
        #   path: nlp/functions/03 tsv
        # - name: patterns
        #   path: patterns/functions/03 tsv
        # - name: synonym
        #   path: synonym/functions/03 tsv
        # - name: util
        #   path: util/functions/03 tsv
